name: TeamChat
author: BauHD
main: dev.bauhd.teamchat.bukkit.BukkitTeamChat
version: '2.0'
api-version: '1.13'
website: https://hangar.papermc.io/BauHD/TeamChat
commands:
  teamchat:
    description: "The TeamChat command."
    aliases: ["tc"]