name: TeamChat
author: BauHD
main: dev.bauhd.teamchat.bukkit.BukkitTeamChat
version: '2.1'
api-version: '1.13'
website: https://modrinth.com/project/teamchat
softdepend: ["PlaceholderAPI"]
commands:
  teamchat:
    description: "The TeamChat command."
    aliases: ["tc"]
  team:
    description: "A command to display your team."