name: TeamChat
author: BauHD
main: dev.bauhd.teamchat.paper.PaperTeamChat
version: '2.1'
api-version: '1.19'
website: https://modrinth.com/project/teamchat
folia-supported: true

dependencies:
  server:
    MiniPlaceholders:
      load: BEFORE
      required: false
    PlaceholderAPI:
      load: BEFORE
      required: false