name: TeamChat
author: BauHD
main: dev.bauhd.teamchat.paper.PaperTeamChat
version: '2.0'
api-version: '1.19'
website: https://modrinth.com/project/teamchat

dependencies:
  server:
    MiniPlaceholders:
      load: AFTER
      required: false