name: TeamChat
author: BauHD
main: dev.bauhd.teamchat.paper.PaperTeamChat
version: '2.0'
api-version: '1.13'
softdepend: ["MiniPlaceholders"]
website: https://modrinth.com/project/teamchat
commands:
  teamchat:
    description: "The TeamChat command."
    aliases: ["tc"]